# Site settings
title: escape(window)
email: aki@escapewindow.com
description: > # this means to ignore newlines until "baseurl:"
  escape(window)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://escapewindow.github.io" # the base hostname & protocol for your site

disqus:
  shortname: escapewindow

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
